import { Router } from "express";
import { verifyJWT } from "../middlewares/auth.middleware.js";
import { addBook,  getBooksBasedOnCategory, getCourseBasedOnCategory, newCourse, removeCourse } from "../controllers/admin.controller.js";
const router=Router();
router.route("/remove-course").post(removeCourse);  
router.route("/recent-course").get(newCourse);
router.route("/getcourse-basedon-category").post(getCourseBasedOnCategory);
router.route("/addbook").post(addBook);
router.route("/getbooks-basedon-category").get(getBooksBasedOnCategory);
export default router;